### ISSUE TITLE
Error popup after denying notifications (denied_not_permanently_already)

### ISSUE THREAD

**Issue by sstefanofm** [KlaasVanDerLinden/cordova-plugin-notifications-permission#4]
*Tested on Android API 34 Emulator.*
After denying the permission twice, either this popup shows every time I open the app:
![image](https://github.com/user-attachments/assets/95a75574-8e90-462a-9444-96481eac8828)
Or the app crashes:
![image](https://github.com/user-attachments/assets/4aae170d-4f25-466c-b4c9-86111a6193ad)

This is the code:
```
document.addEventListener('deviceready', function () {
      const notifPlug = window.cordova.notifications_permission
      notifPlug.maybeAskPermission(
        function (status) {
          console.log('[DEBUG] [stf] maybeAskPermission status: ' + status)
        }, {
          show: true, /* show the rationale dialog */
          title: 'This is a title',
          msg: 'This is msg test test test',
          okButton: 'oK',
          cancelButton: 'Cancel',
        }, {
          show: true,
          title: 'Last resort title',
          msg: 'TESTESTEST',
          okButton: 'OK',
          cancelButton: 'CancelButton'
        }
      )
}, false)

**Comment by sstefanofm** [comment]
If I change to `show: false` in the last_resort dialog settings, the app doesn't crash... but shows the Error alert.

**Comment by KlaasVanDerLinden** [comment]
I published a new version. Can you test it? And maybe find out why you couldn't fix it? Somehow there is a deprecation of onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) 
And cordova didn't support the new version. It might do now and therefore should be implemented properly.

**Comment by sstefanofm** [comment]
Hiii I am testing it right now...
I updated to 0.0.32

I've put `show: true` on both rationale and last restort dialogs. 

The app doesn't crash but the error alert still shows. The alert shows everytime I "Don't Allow" the permissions. After denying twice, the Error alert shows everytime I open the app (after it being closed (freshly opened)).

Also, the rationale dialog sometimes shows after the "2nd" time the permission is requested. The last resort dialog is not showing.

There's no problem when granting permissions.

One thing I didn't mention is that the project I'm running is on Capacitor v6, so the cordova plugins are managed with *capacitor-cordova-android-plugins* https://www.npmjs.com/package/@capacitor/android 

*Edit: Tested on Android 14*

**Comment by sstefanofm** [comment]
I'm also using this plugin https://www.npmjs.com/package/@capacitor/push-notifications 
Maybe the plugins are colliding each other?
Can you replicate my error?

**Comment by sstefanofm** [comment]
Yes, indeed, the plugins were colliding each other.
The problem was that i was requesting permissions with both plugins. I commented the request permission of @capacitor/push-notifications and the error alert didn't show anymore.
The plugin is working as intended.
<3

*Edit: the rationale and last resort dialogs are showing*
